-- Tag X MVP schema for Supabase/Postgres
create extension if not exists "pgcrypto";

create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, created_at timestamptz not null default now());
create table public.teams (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null, short_name text, crest_url text, created_at timestamptz not null default now());
create table public.players (id uuid primary key default gen_random_uuid(), team_id uuid not null references public.teams(id) on delete cascade, name text not null, shirt_number integer, position text, active boolean not null default true, created_at timestamptz not null default now());
create table public.matches (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, home_team_id uuid references public.teams(id), away_team_id uuid references public.teams(id), match_date timestamptz, competition text, venue text, video_path text, status text not null default 'draft' check (status in ('draft','tagging','complete')), created_at timestamptz not null default now());
create table public.event_types (id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id) on delete cascade, name text not null, shortcut integer, requires_destination boolean not null default false, requires_goal_frame boolean not null default false, is_default boolean not null default false, sort_order integer not null default 0, unique nulls not distinct (organization_id,name));
create table public.outcomes (id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id) on delete cascade, name text not null, is_default boolean not null default false, unique nulls not distinct (organization_id,name));
create table public.match_events (id uuid primary key default gen_random_uuid(), match_id uuid not null references public.matches(id) on delete cascade, team_id uuid references public.teams(id), player_id uuid references public.players(id), event_type_id uuid not null references public.event_types(id), outcome_id uuid references public.outcomes(id), video_second numeric(10,3) not null, period smallint not null default 1, x numeric(5,2), y numeric(5,2), end_x numeric(5,2), end_y numeric(5,2), phase text, note text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index match_events_match_time_idx on public.match_events(match_id,video_second);
create index players_team_idx on public.players(team_id);

insert into public.event_types (name,shortcut,requires_destination,requires_goal_frame,is_default,sort_order) values
('Pass',1,true,false,true,1),('Shot',2,false,true,true,2),('Cross',3,true,false,true,3),('Carry',4,true,false,true,4),('Recovery',5,false,false,true,5),('Tackle',6,false,false,true,6),('Interception',7,false,false,true,7),('Clearance',8,true,false,true,8),('Aerial duel',9,false,false,true,9),('Foul',null,false,false,true,10),('Save',null,false,true,true,11),('Ball out',null,false,false,true,12),('Offside',null,false,false,true,13);
insert into public.outcomes (name,is_default) values ('Successful',true),('Unsuccessful',true),('Goal',true),('Blocked',true),('Saved',true),('Off target',true),('Won',true),('Lost',true),('Retained',true),('Turnover',true);
