"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type EventRecord = { id:number; minute:string; team:"RIV"|"BOC"; player:string; action:string; outcome:string; x:number; y:number };
const actions=["Pass","Shot","Cross","Carry","Recovery","Tackle","Interception","Clearance","Aerial duel","Foul"];
const outcomes=["Successful","Unsuccessful","Goal","Blocked","Saved","Off target","Won","Lost"];
const players=["01 F. Armani","02 S. Boselli","03 R. Funes Mori","05 M. Kranevitter","08 N. Fernández","10 M. Lanzini","11 F. Colidio","19 C. Echeverri"];
const seededEvents:EventRecord[]=[
 {id:128,minute:"42:08",team:"RIV",player:"10 M. Lanzini",action:"Pass",outcome:"Successful",x:32,y:61},
 {id:127,minute:"41:54",team:"RIV",player:"11 F. Colidio",action:"Shot",outcome:"Blocked",x:84,y:42},
 {id:126,minute:"41:31",team:"BOC",player:"09 M. Merentiel",action:"Recovery",outcome:"Won",x:57,y:72},
 {id:125,minute:"40:48",team:"RIV",player:"08 N. Fernández",action:"Cross",outcome:"Successful",x:92,y:18},
];
const panelOptions=[
 {id:"phase",label:"Phase analysis",detail:"Build-up, press, transition and block"},
 {id:"goal",label:"Goal frame",detail:"Shot placement and goalkeeper outcome"},
 {id:"note",label:"Quick note",detail:"Add context without leaving the flow"},
 {id:"clip",label:"Clip controls",detail:"Pre-roll, post-roll and playlist"},
];

function TagXMark(){return <div className="brand-mark" aria-hidden="true"><span>T</span><b>X</b></div>}
function MiniPitch(){return <div className="mini-pitch" aria-label="Football pitch overview"><div className="pitch-line halfway"/><div className="pitch-circle"/><div className="pitch-box left"/><div className="pitch-box right"/></div>}

export default function Home(){
 const [view,setView]=useState<"tagging"|"illustrator">("tagging");
 const [configOpen,setConfigOpen]=useState(false),[rosterOpen,setRosterOpen]=useState(false),[playing,setPlaying]=useState(false);
 const [clock,setClock]=useState(2531),[activeAction,setActiveAction]=useState("Pass"),[activeOutcome,setActiveOutcome]=useState("Successful"),[activePlayer,setActivePlayer]=useState(players[5]);
 const [activeTeam,setActiveTeam]=useState<"RIV"|"BOC">("RIV"),[events,setEvents]=useState(seededEvents),[enabledPanels,setEnabledPanels]=useState(["phase","goal","clip"]),[toast,setToast]=useState(""),[tool,setTool]=useState("Arrow");
 const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(!playing)return;const timer=window.setInterval(()=>setClock(c=>c+1),1000);return()=>window.clearInterval(timer)},[playing]);
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.code==="Space"&&!(e.target instanceof HTMLInputElement)){e.preventDefault();setPlaying(p=>!p)}const i=Number(e.key)-1;if(i>=0&&i<actions.length)setActiveAction(actions[i]);if(e.key==="Escape"){setConfigOpen(false);setRosterOpen(false)}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)},[]);
 const formattedClock=useMemo(()=>`${String(Math.floor(clock/60)).padStart(2,"0")}:${String(clock%60).padStart(2,"0")}`,[clock]);
 function showToast(message:string){setToast(message);window.setTimeout(()=>setToast(""),2200)}
 function addEvent(e:React.MouseEvent<HTMLDivElement>){const rect=e.currentTarget.getBoundingClientRect(),x=Math.round(((e.clientX-rect.left)/rect.width)*100),y=Math.round(((e.clientY-rect.top)/rect.height)*100);const next:EventRecord={id:events[0].id+1,minute:formattedClock,team:activeTeam,player:activePlayer,action:activeAction,outcome:activeOutcome,x,y};setEvents([next,...events]);showToast(`${activeAction} tagged · ${activePlayer}`)}
 function togglePanel(id:string){setEnabledPanels(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id])}
 return <main className="app-shell">
  <aside className="sidebar">
   <div className="brand"><TagXMark/><div><strong>TAG X</strong><span>VIDEO INTELLIGENCE</span></div></div>
   <div className="project-card"><span className="eyebrow">ACTIVE MATCH</span><strong>River Plate <b>2</b> — <b>1</b> Boca Juniors</strong><small>El Monumental · Friendly</small></div>
   <nav aria-label="Primary navigation"><button className={view==="tagging"?"active":""} onClick={()=>setView("tagging")}><span>⌾</span> Match tagging</button><button className={view==="illustrator"?"active":""} onClick={()=>setView("illustrator")}><span>✎</span> Illustrator</button></nav>
   <div className="side-lower"><button className="ghost-row" onClick={()=>setRosterOpen(true)}><span>♙</span> Teams & rosters <b>›</b></button><button className="ghost-row" onClick={()=>setConfigOpen(true)}><span>⚙</span> Workspace controls <b>›</b></button><div className="shortcut-card"><span>KEYBOARD</span><p><kbd>Space</kbd> play / pause</p><p><kbd>1–9</kbd> choose event</p><p><kbd>Esc</kbd> close panels</p></div><div className="user-card"><span>FC</span><div><strong>Felipe Chiesa</strong><small>Lead analyst</small></div><b>···</b></div></div>
  </aside>
  <section className="workspace">
   <header className="topbar"><div><p>{view==="tagging"?"MATCH TAGGING":"ILLUSTRATOR"}</p><h1>{view==="tagging"?"River Plate vs Boca Juniors":"Tactical clip · 41:54"}</h1></div><div className="top-actions"><span className="live-pill"><i/> {playing?"TRACKING":"READY"} · {formattedClock}</span><button onClick={()=>showToast("Session saved")}>Save</button><button className="primary" onClick={()=>showToast(view==="tagging"?"Export prepared":"Render queued")}>{view==="tagging"?"Export":"Render video"}</button></div></header>
   {view==="tagging"?<div className="tagging-layout">
    <section className="video-column"><div className="video-stage" onClick={()=>setPlaying(p=>!p)}><div className="stadium-bg"><div className="stadium-pitch"><MiniPitch/></div></div><div className="scorebug"><b>RIV</b><strong>2 — 1</strong><b>BOC</b><span>2nd half</span></div>{!playing&&<button className="play-big" aria-label="Play video">▶</button>}<div className="video-hint">Click video or press Space to {playing?"pause":"play"}</div></div>
     <div className="transport"><button onClick={()=>setClock(c=>Math.max(0,c-5))}>−5s</button><button className="transport-main" onClick={()=>setPlaying(p=>!p)}>{playing?"Ⅱ Pause":"▶ Play"}</button><button onClick={()=>setClock(c=>c+5)}>+5s</button><div className="timeline"><span style={{width:`${(clock/5400)*100}%`}}/></div><b>{formattedClock}</b><small>/ 90:00</small><button className="upload" onClick={()=>fileRef.current?.click()}>＋ Video</button><input ref={fileRef} type="file" accept="video/*" hidden onChange={()=>showToast("Video loaded")}/></div>
     <div className="lower-grid"><div className="pitch-card card"><div className="card-heading"><div><span className="eyebrow">LOCATION</span><h2>Click where it happened</h2></div><span className="mode-pill">{activeAction} · origin</span></div><div className="tag-pitch" onClick={addEvent} role="button" tabIndex={0} aria-label="Tag event location on pitch"><MiniPitch/>{events.slice(0,9).map(event=><i key={event.id} className={`event-dot ${event.team.toLowerCase()}`} style={{left:`${event.x}%`,top:`${event.y}%`}}/>)}<div className="direction">ATTACKING DIRECTION →</div></div></div>
      <div className="recent-card card"><div className="card-heading"><div><span className="eyebrow">LIVE LOG</span><h2>Recent events</h2></div><button onClick={()=>setEvents(events.slice(1))}>Undo</button></div><div className="event-list">{events.slice(0,6).map(event=><button key={event.id} onClick={()=>setClock(Number(event.minute.split(":")[0])*60+Number(event.minute.split(":")[1]))}><time>{event.minute}</time><span className={`event-icon ${event.team.toLowerCase()}`}>{event.action[0]}</span><div><strong>{event.action}</strong><small>{event.player} · {event.outcome}</small></div><b>›</b></button>)}</div></div></div>
    </section>
    <aside className="tag-panel"><div className="tag-panel-head"><div><span className="eyebrow">QUICK TAG</span><h2>Record event</h2></div><button aria-label="Configure panels" onClick={()=>setConfigOpen(true)}>⚙</button></div>
     <div className="step"><span>01</span><label>Team</label></div><div className="segmented"><button className={activeTeam==="RIV"?"selected":""} onClick={()=>setActiveTeam("RIV")}><i className="team-dot river"/> River Plate</button><button className={activeTeam==="BOC"?"selected":""} onClick={()=>setActiveTeam("BOC")}><i className="team-dot boca"/> Boca Juniors</button></div>
     <div className="step"><span>02</span><label>Player</label><button onClick={()=>setRosterOpen(true)}>Edit squad</button></div><select value={activePlayer} onChange={e=>setActivePlayer(e.target.value)}>{players.map(player=><option key={player}>{player}</option>)}</select>
     <div className="step"><span>03</span><label>Action</label><button onClick={()=>showToast("Custom event added")}>＋ Add</button></div><div className="action-grid">{actions.map((action,index)=><button key={action} className={activeAction===action?"selected":""} onClick={()=>setActiveAction(action)}><kbd>{index+1}</kbd>{action}</button>)}</div>
     <div className="step"><span>04</span><label>Outcome</label><button onClick={()=>showToast("Custom outcome added")}>＋ Add</button></div><div className="outcome-grid">{outcomes.map(outcome=><button key={outcome} className={activeOutcome===outcome?"selected":""} onClick={()=>setActiveOutcome(outcome)}><i/>{outcome}</button>)}</div>
     {enabledPanels.includes("phase")&&<div className="optional-panel"><div><span>PHASE ANALYSIS</span><small>Optional control</small></div><select defaultValue="Build-up"><option>Build-up</option><option>High press</option><option>Counter attack</option><option>Low block</option><option>Transition</option></select></div>}
     {enabledPanels.includes("clip")&&<div className="clip-row"><span>Clip</span><button>− 5s</button><strong>{formattedClock}</strong><button>＋ 5s</button></div>}<button className="commit" onClick={()=>showToast("Click a location on the pitch")}>Next: choose location <span>→</span></button>
    </aside>
   </div>:<div className="illustrator-layout"><section className="canvas-card"><div className="canvas-head"><div><span className="eyebrow">TACTICAL CANVAS</span><h2>Counter-press after loss</h2></div><div><button onClick={()=>showToast("Canvas cleared")}>Clear</button><button className="primary" onClick={()=>showToast("Frame saved")}>Save frame</button></div></div><div className="illustrator-canvas"><div className="stadium-bg"><div className="stadium-pitch"><MiniPitch/></div></div><div className="draw-ring one"/><div className="draw-ring two"/><div className="draw-arrow a1">➜</div><div className="draw-arrow a2">➜</div><div className="draw-zone"/><div className="frame-time">00:41:54.2</div></div><div className="sequence-bar"><button>▶ Preview</button><div><span style={{width:"68%"}}/></div><time>00:08.0</time></div></section>
    <aside className="tools-card"><span className="eyebrow">DRAWING TOOLS</span><h2>Annotate the play</h2><div className="tools-grid">{["Select","Player ring","Spotlight","Arrow","Curved arrow","Link line","Distance","Area","Text"].map(item=><button key={item} className={tool===item?"selected":""} onClick={()=>setTool(item)}><span>{item==="Arrow"?"↗":item==="Area"?"◇":item==="Text"?"T":"○"}</span>{item}</button>)}</div><div className="style-controls"><label>Line colour <input type="color" defaultValue="#5784e6"/></label><label>Fill colour <input type="color" defaultValue="#d1e8ff"/></label><label>Opacity <input type="range" defaultValue="75"/></label><label>Stroke <input type="range" defaultValue="60"/></label></div><div className="frames"><div><span className="eyebrow">SEQUENCE</span><button>＋ Frame</button></div>{["41:52.0","41:54.2","41:57.8"].map((time,index)=><button key={time} className={index===1?"selected":""}><b>{index+1}</b><span>{time}<small>{index===1?"Current frame":"Match clip"}</small></span><strong>⋮</strong></button>)}</div></aside></div>}
  </section>
  {configOpen&&<div className="modal-backdrop" onMouseDown={()=>setConfigOpen(false)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><header><div><span className="eyebrow">WORKSPACE CONTROLS</span><h2>Keep only what you need</h2><p>Optional panels appear inside Match Tagging, never as extra navigation.</p></div><button onClick={()=>setConfigOpen(false)}>×</button></header><div className="option-list">{panelOptions.map(panel=><button key={panel.id} onClick={()=>togglePanel(panel.id)}><span className={enabledPanels.includes(panel.id)?"toggle on":"toggle"}><i/></span><div><strong>{panel.label}</strong><small>{panel.detail}</small></div></button>)}</div><footer><button onClick={()=>setEnabledPanels([])}>Hide all</button><button className="primary" onClick={()=>setConfigOpen(false)}>Apply controls</button></footer></section></div>}
  {rosterOpen&&<div className="modal-backdrop" onMouseDown={()=>setRosterOpen(false)}><section className="modal roster-modal" onMouseDown={e=>e.stopPropagation()}><header><div><span className="eyebrow">TEAM LIBRARY</span><h2>River Plate · First team</h2><p>Save this squad once and import it into future matches.</p></div><button onClick={()=>setRosterOpen(false)}>×</button></header><div className="roster-actions"><button className="primary" onClick={()=>showToast("Team saved to library")}>Save team to library</button><button>Import saved team</button><button>＋ Player</button></div><div className="roster-table">{players.map((player,index)=><div key={player}><span>{String(index+1).padStart(2,"0")}</span><strong>{player.slice(3)}</strong><small>{index<3?"DEF":index<5?"MID":"ATT"}</small><button>•••</button></div>)}</div></section></div>}
  {toast&&<div className="toast"><i/>{toast}</div>}
 </main>
}
